### ISSUE TITLE
Downloading UKESM data on mass-cli1.jasmin.ac.uk

### ISSUE THREAD

**Issue by ledm** [valeriupredoi/bgcval2#10]
So, bgcval has a command line tool to automatically download ukesm data via the Met Office data system, Mass using moose:

https://github.com/valeriupredoi/bgcval2/blob/main/bgcval2/bgcvaltools/downloadFromMass.py

The tool should be updated to python3, and included as a command within bgcval2. It must run on a specific vm on jasmin, mass-cli1.jasmin.ac.uk, and won't work elsewhere. 

There is an executable script which calls it via ssh available too: https://github.com/valeriupredoi/bgcval2/blob/main/bgcval2/RemoteScripts/downloadOnMassCli.sh

The command line argument "noMoo" needs to be replaced with "dry-run" or similar. 

The file naming scheme that it uses is a bit archaic, so it might be sensible to changed that later.

**Comment by valeriupredoi** [comment]
that is Py3 - I've Py3-ed everything :grin: I'll have a look at using that via the shell script, on mass-cli, and will see what we need to do :+1:

**Comment by ledm** [comment]
This is probably the main thing that is missing now. This is the script that downloads the model data and adjusts the file naming convention to match what bgcval2 expects.

**Comment by ledm** [comment]
I'm working on this in a branch `new_mass_download` - which I will push at some point. 

The jobs are:
- [ ] add download_from_mass to setup.sh (done! it's now interactive)
- [ ] add download_from_mass to analysis_compare and to input yaml interface.
- [ ] Figure out how to send the download from sci1 to mass-cli1.  Might need some help here @valeriupredoi.
   - [ ] Can't download on sci1 and can't ssh from sci1 to mass-cli1.
   - [ ] output the download script as a .sh file then run it on mass-cli1 (or from cron-machine, jasmin lander - or some remote desk top, but whatever method needs to work for everyone. )

**Comment by valeriupredoi** [comment]
think this is fixed now eh @ledm - reopen if you still wanna work on it pls :+1:
