### ISSUE TITLE
Missing geographical regions

### ISSUE THREAD

**Issue by DrYool** [valeriupredoi/bgcval2#103]
I can't see why, but several large regions are no longer producing output. These are the North Atlantic, North Pacific and South Pacific, but not - weirdly - the South Atlantic. This can be seen in a number of recent jobs, for example: 

https://gws-access.jasmin.ac.uk/public/esmeval/CompareReports/bgcval2/ayool/ukesm_oae_rate/#OtherPlots-AirSeaFlux

**Comment by ledm** [comment]
I'll add these into PR #102 as it already adds several new regions.

**Comment by ledm** [comment]
The regions I'm including now are:
```
regions         : Global ignoreInlandSeas SouthernOcean ArcticOcean Equator10 NorthPacificOcean SouthPacificOcean NorthAtlanticOcean  SouthAtlanticOcean
```
Are these enough?

**Comment by ledm** [comment]
We can add any regions or cuts from https://github.com/valeriupredoi/bgcval2/blob/main/bgcval2/bgcvaltools/makeMask.py

There are a lot of them!

**Comment by ledm** [comment]
I see in #104 that you also use `OnShelf OffShelf` regions. Do you want me to add them in as well? Or just keep them for MLD?

**Comment by DrYool** [comment]
Hi Lee. I added these specifically for the alkalinity analysis I was doing. I don't know how important they are otherwise. So don't worry about them. Anyway, I can see that some of the other areas I requested are now online, so that's good. Cheers.
