### ISSUE TITLE
Mixed layer depth issues

### ISSUE THREAD

**Issue by DrYool** [valeriupredoi/bgcval2#104]
There seem to be issues with mixed layer depth in current suites. For instance:

https://gws-access.jasmin.ac.uk/public/esmeval/CompareReports/bgcval2/ldemora/TerraFIRMA_overshoot_historical/#OtherPlots-MLD

I previously had trouble with this and resolved it (to a degree) by creating a new diagnostic (mld2.yml) that I've pasted in below.

```
---
name            : MLD2
units           : m
model           : NEMO
modelgrid       : eORCA1
dimensions      : 2
modelFiles      : $BASEDIR_MODEL/$JOBID/nemo*$JOBIDo_1y_*_grid-T.nc
model_vars      : mlotst
model_convert   : NoChange
layers          : layerless
regions         : Global OnShelf OffShelf ignoreInlandSeas SouthernOcean ArcticOcean Equator10 NorthAtlanticOcean SouthAtlanticOcean NorthPacificOcean SouthPacificOcean #;Remainder NorthernSubpolarAtlantic NorthernSubpolarPacific
```

**Comment by ledm** [comment]
We were previously looking at MLD from `somxl010` `somxzint1`. I think that different versions of NEMO output different names. I'd guess we'll have to keep this backwards compatible, so we can't just copy this code in.

**Comment by DrYool** [comment]
These seem to be working correctly now. One or two region gaps, but I suspect that's just the suite processing lagging. Happy to sign off on this.
