### ISSUE TITLE
Single model HTML report path is hard-wired in makeReport.py

### ISSUE THREAD

**Issue by ledm** [valeriupredoi/bgcval2#12]
Just saw that the HTML report path is hard-wired, in makeReport.py

I think it should be set in the paths script.

The default location is fine though:
```
    reportdir = folder('reports/' + jobID)
```

**Comment by ledm** [comment]
There's several issues with html code in makeReport.py

The paths are hardwire relative paths, so it would be good to set them to dynamic absolute paths - so they are set in paths.py and fixed.

**Comment by ledm** [comment]
Working on this here: https://github.com/valeriupredoi/bgcval2/tree/fix_make_report

**Comment by valeriupredoi** [comment]
get the home dir like this:
```python
from pathlib import Path
home = str(Path.home())
```

**Comment by ledm** [comment]
I didn't mean  the users home direction, but the path to the bgcval2 repository. I found a fix though! I'll do a PR.

**Comment by valeriupredoi** [comment]
the bgcval2 install repo? Or where the user puts their outputs? I'll check out the PR :+1:
