### ISSUE TITLE
BGCVal2 is now fully packaged

### ISSUE THREAD

**Issue by valeriupredoi** [valeriupredoi/bgcval2#2]
OK this is now fully packaged with Python=3.9; a PyPi binary can be done as it's run via a nightly test [here](https://github.com/valeriupredoi/bgcval2/runs/6276163409?check_suite_focus=true); all imports have now been fixed and the tool can now be deployed on whatever machine - JASMIN most probably; @ledm note that I also fixed the paths stuff, the user doesn't have to do anything now, it detects automatically where it runs, and who is running it. I think I am actually ready for a first release but it'd be good if we got some testing done (am running `level2` on JASMIN as we speak tho). Alas, it will need some serious documentation, but given I've not changed any of its previous functionality, the documentation should be the same as per previous :+1:

**Comment by ledm** [comment]
I'm hoping to set up a trial run on jasmin today, provided nothing too nuts gets dropped on me before then. Cheers!

**Comment by valeriupredoi** [comment]
OK closing this - the package is REAL :grin:
