### ISSUE TITLE
Comparison reports - new interface

### ISSUE THREAD

**Issue by ledm** [valeriupredoi/bgcval2#22]
I'm working on improving the interface for the comparison reports. It'll be set up so it can be directed to run from an yml, instead of hard wired into analysis_compare.py.

When this is done, I could use some help with make_reports.py @valeriupredoi, as the path to the html5 assets is hard-wired into the code. It would be better if it were path agnostic. ie:
https://github.com/valeriupredoi/bgcval2/blob/0eacaebe086e09ac8860eabcdafa7210dd94920b/bgcval2/makeReport.py#L1292

**Comment by ledm** [comment]
Okay, I think this is now fully working. It took quite a lot of wide ranging changes, and a few not-directly related changes also made it into this branch. But here's a solid PR that I'm happy with. 

I'm currently running a full analysis suite for Till. If it works and the output compares well to BGC-val (v1), I'll move towards the PR.

After this, the next job is to figure out how to run download_from_mass. After that, Till, Andrew and Julien can run their own BGC-vals!

**Comment by valeriupredoi** [comment]
awesome, I'll have a look in a jiffy! :beer:

**Comment by valeriupredoi** [comment]
dis done (I believe)
