### ISSUE TITLE
analysis_compare: run "key metrics first" first

### ISSUE THREAD

**Issue by ledm** [valeriupredoi/bgcval2#25]
In the original bgc-val, we had a small number of fast key metrics to quickly populate an analysis. It would be handy to set analysis_compare to run them first before running the longer ones.

**Comment by valeriupredoi** [comment]
what does that mean? Anything I should do wrt code structure?

**Comment by ledm** [comment]
It's just a case of adding a few lines to analysis_compare. I'll do it.

**Comment by valeriupredoi** [comment]
shweet :beer:

**Comment by valeriupredoi** [comment]
did you do this, bud?

**Comment by ledm** [comment]
Yeah, pretty much, but better. analsysis_compare now accepts a list of keys, then runs them one at a time.
