### ISSUE TITLE
Comments from the first run

### ISSUE THREAD

**Issue by ledm** [valeriupredoi/bgcval2#3]
Firstly, installation was very easy. Awesome! Great work @valeriupredoi.

Secondly, running a time series analysis was also very easy! Awesome.

README
----------

I noticed a couple minor things in the README:

- Readme doesn't say anywhere to make a local clone of the repository. (Very basic, but important for new users.)

- Can we change the environment to bgcval2:
```
mamba env create -n bgcval2 -f environment.yml
```

- This doesn't make tons of sense, as level2 is actually the point to point analysis, not part of the time series analysis.
```
analysis_timeseries u-bc179 level2
```

- I'll write some explanations for the Available executables table in the README. 

So only very minor changes so far. 

Additional scripts:
--------------------

One of the key missing parts so far is the download from mass. This is the script
- bgcval2/bgcvaltools/downloadFromMass.py

But it only works on machines where the mass/moose system is set up. There's a dedicated jasmin VM, mass-cli1.jasmin.ac.uk for this. Is there some way to create a command which sends a job to the mass-cli1.jasmin.ac.uk machine from sci1?

Changes to active scripts:
-----------------------------
timeseries:
- it would be nice to have some easy way to edit the list of variables to analyse. What would be a good way to do that? yaml?
- I think the shelve and images paths overlaps with my previous paths. I'd like to be able to send them to a bgcval2 specific path, so as to not confuse this with runs happening elsewhere.

Compare report:
- this needs some straight forward way to specify all the details needed to run a single comparison.

(I'm not suggesting that you should do this @valeriupredoi, but I'd like your input on it!)

**Comment by valeriupredoi** [comment]
cheers much, dude! Let me address as many of these points now, and the ones I can't do on the spot I'll open separate issues, so we discuss there (and on the phone too :phone: )

**Comment by valeriupredoi** [comment]
looks to me that these have been addressed - we're a long way since May, great work @ledm :beer:
