### ISSUE TITLE
Command line help commands?

### ISSUE THREAD

**Issue by ledm** [valeriupredoi/bgcval2#32]
None of the functions (that I wrote - me culpa!) in bcgval2 seem to work with the -h or --help command line arguments.

Is there any chance you could help me with that @valeriupredoi? If you write a interface useful and I fill out the text. #TeamWork

TBH, while this may be useful for other users, it would be great for me too, as I often forget how things work and what options are available. 

Cheers!

**Comment by ledm** [comment]
Here are the files that need help sections:

- [ ] analysic_compare.py (this actually does almost everything now so perhaps should be renamed)
- [ ] download_from_mass.py
- [ ] analysis_timeseries.py
- [ ] bgcval2_make_report.py
- [ ] bgcval.py (this used to be thewholepackage, but it needs to be framed in a clearer way.)

**Comment by valeriupredoi** [comment]
OK will do that :+1:
