### ISSUE TITLE
[Testing] Can we run a set of very simple analyses with basic (and small) data

### ISSUE THREAD

**Issue by valeriupredoi** [valeriupredoi/bgcval2#36]
It'd be good if we could run a set of very basic analyses (one for each of the executables we maintain atm) so we we can get some standard output and test for that output. This is what's called a regression test - basically run this test (or tests) everytime there is a functional change and hope for the same output. At the moment the test we have only tests the loading of the executable and its submodules, which is a good start, but not much else :grin:

**Comment by ledm** [comment]
A lot of the tools have a minomal testing key, `debug`, which only runs one or two variables.

And of course, `analysis_compare` includes:
- download from mass
- analysis time series
- report maker.

So the bulk of the testing could be done in a single command. 

The hard part would be finding a couple sensible but small jobIDs that we could run and make sure they work.

**Comment by valeriupredoi** [comment]
download from MASS will not work on a testing machine like Circle or Github Actions (we currently have only Github Actions and I don't see a point for Circle or Travis or other CI platform on top of it, but anyway) - so GA tests, can we pack that data that is off MASS and include it here in a testing data repo (note: for GitHub we must have tiny bits of data)? We can test at least some parts of download from mass if we just do `--dry-run` (?)

**Comment by ledm** [comment]
> download from MASS will not work on a testing machine like Circle or Github Actions (we currently have only Github Actions and I don't see a point for Circle or Travis or other CI platform on top of it, but anyway) - so GA tests, can we pack that data that is off MASS and include it here in a testing data repo (note: for GitHub we must have tiny bits of data)? We can test at least some parts of download from mass if we just do `--dry-run` (?)

I'm okay with that. Test the dry-run part.

**Comment by valeriupredoi** [comment]
good, ket's do it that way then, I need your magic for data and test run calls (actual commands), then I can write up the tests, and see how long/how much output they generate, then write the comparisons calls. If we pull this cleanly we might be able to skip unit testing - frankly, I have no appetite to write unit tests for all those gazillion lines functions :laughing:
