### ISSUE TITLE
Basemap removal

### ISSUE THREAD

**Issue by ledm** [valeriupredoi/bgcval2#4]
Basemap is obsolete now. 

Solution: Replace it with Cartopy. 

**V Note**: The current import `from mpl_toolkits.basemap import Basemap` still works fine with `basemap` for Python 3.8 and 3.9, which we currently support. We'll have to move to Python 3.10 eventually and then we'll need to move away from Basemap.

**Comment by valeriupredoi** [comment]
we moved to Python 3.10 and still support `basemap` (legacy) for 3.10 - we shouldn't do any more devving with it though
