### ISSUE TITLE
Dealing with changes in coordinate names in their netcdfs outputs

### ISSUE THREAD

**Issue by ledm** [valeriupredoi/bgcval2#44]
So I'm testing PR #43 with a quick debug job based on a couple recent UKESM jobs, and I've run in to the annoying situation that two subsequent jobs have different coordinates! 

`u-cp416` uses `nav_lat` but `u-cp647` uses `nav_lat_grid`! Fricking NEMO! You get used to one thing and can't guarantee that they won't randomly change everything again!

To get this working, I'm going to have to change a whole bunch of other stuff of the interface. Annoying.

**Comment by ledm** [comment]
Need to figure out if it's worth the effort of changing everything for the edge cases of when we have several different NEMO formats in the same comparison, or whether we should just set it and forget.

Perhaps the trick would be to have several directories for `key_files` ie:
- `bgcval2`
  -  `key_files`
    -  `NEMO3.8`
      - `temperature.yml      
    -  `NEMO4.0`
      - `temperature.yml

**Comment by ledm** [comment]
THis 

> Need to figure out if it's worth the effort of changing everything for the edge cases of when we have several different NEMO formats in the same comparison, or whether we should just set it and forget.
> 
> Perhaps the trick would be to have several directories for `key_files` ie:
> 
> * `bgcval2`
>   
>   * `key_files`
>   * `NEMO3.8`
>     - `temperature.yml`
>   * `NEMO4.0`
>     - `temperature.yml`

Not so sure about this proposal. I think it might be better to use the model name and datasource name ion the key_files to determine the coordinate naming though this would mean another set of yaml configs, which no one wants! Better than having to re-create every single file in key_files every time NEMO changes something.

**Comment by ledm** [comment]
I think I'll just provide a list of potential names for coordinates and let bgc-val select the best one. Is that bad, lazy or smart?

**Comment by valeriupredoi** [comment]
> I think I'll just provide a list of potential names for coordinates and let bgc-val select the best one. Is that bad, lazy or smart?
> 
> It's similar to how bgcval v1 worked.
that's the way I'd do it if there's be no change to be applied (eg a prefactor, or some scalar to be applied - even then - these can be done on the fly)
