### ISSUE TITLE
end-to-end test needed

### ISSUE THREAD

**Issue by valeriupredoi** [valeriupredoi/bgcval2#54]
I am looking at implementing an end to end test that we can run on the CI so we can test output validity (regression testing): @ledm you suggested using `analysis_compare -y input_yml/debug.yml` - which has a number of catches:

- throws an error if one doesn't run it on wither JASMIN or PML - the test needs to run on a Github Actions virtual machine which is neither of those (fixable)
- throws a Permissions denied error on JASMIN because `download_from_mass` module needs to perform an `os.chmod` on data that is not chmod-able by other tha the owner:

```bash
(bgval2) [valeriu@sci2 bgcval2]$ analysis_compare -y input_yml/debug.yml
analysis_timeseries: Comparison config file input_yml/debug.yml
---------------------
timeseries_compare: debug_49
job ids: dict_keys(['u-cp416debug'])
u-cp416debug description: GC5 N96 ORCA1 spin-up 3
u-cp416debug colour: purple
u-cp416debug line thickness & style: 0.7 -
u-cp416debug Shift time by 0.0
u-cp416debug suite: debug
Traceback (most recent call last):
  File "/home/users/valeriu/miniconda3-June2021/envs/bgval2/bin/analysis_compare", line 33, in <module>
    sys.exit(load_entry_point('BGCVal2', 'console_scripts', 'analysis_compare')())
  File "/home/users/valeriu/bgcval2/bgcval2/analysis_compare.py", line 3318, in main
    load_yml_and_run(compare_yml, config_user)
  File "/home/users/valeriu/bgcval2/bgcval2/analysis_compare.py", line 3239, in load_yml_and_run
    download_from_mass(jobID, doMoo=do_mass_download)
  File "/home/users/valeriu/bgcval2/bgcval2/download_from_mass.py", line 404, in download_from_mass
    os.chmod(outputFold, 0o2775)
PermissionError: [Errno 13] Permission denied: '/gws/nopw/j04/ukesm/BGC_data/u-cp416debug/'
```

This latter one is fixable too - but I need to know what data is needed, and that will determine the feasibility of running it on a Github Actions machine too, we have to have this data stored inside the source code repo (example/sample data) so the test can have access to it instantly, so it must be small in size :beer:

**Comment by valeriupredoi** [comment]
PS it's really not a good idea to change dir/file permissions during a Python session runtime - this can lead to a lot of wondrous/head-scratching behaviour

**Comment by valeriupredoi** [comment]
PS2 - what's going on with these files BTW? They seem to be symlinks created inside the same dir?
```
(bgval2) [valeriu@sci2 bgcval2]$ ls -la /gws/nopw/j04/ukesm/BGC_data/u-cp416/nemo_u-cp416o_1y_26091201-26101201_grid-W.nc
lrwxrwxrwx 1 ldemora users 79 Aug 17 18:02 /gws/nopw/j04/ukesm/BGC_data/u-cp416/nemo_u-cp416o_1y_26091201-26101201_grid-W.nc -> /gws/nopw/j04/ukesm/BGC_data/u-cp416/nemo_cp416o_1y_26091201-26101201_grid-W.nc
(bgval2) [valeriu@sci2 bgcval2]$ ls -la /gws/nopw/j04/ukesm/BGC_data/u-cp416/nemo_cp416o_1y_26091201-26101201_grid-W.nc
-rw-r--r-- 1 ldemora gws_ukesm 54792279 Aug 17 18:02 /gws/nopw/j04/ukesm/BGC_data/u-cp416/nemo_cp416o_1y_26091201-26101201_grid-W.nc
```

**Comment by valeriupredoi** [comment]
I commented out that line that does permissions changes, but the `debug` still stalls:

```
NOT Changing FLAG: $USERNAME to valeriu in /gws/nopw/j04/esmeval/bgc-val/mesh_mask_eORCA1_wrk.nc
NOT Changing FLAG: $BASEDIR_MODEL to /gws/nopw/j04/ukesm/BGC_data in /gws/nopw/j04/esmeval/bgc-val/mesh_mask_eORCA1_wrk.nc
NOT Changing FLAG: $BASEDIR_OBS to /gws/nopw/j04/esmeval/example_data/bgc in /gws/nopw/j04/esmeval/bgc-val/mesh_mask_eORCA1_wrk.nc
NOT Changing FLAG: $PATHS_GRIDFILE to /gws/nopw/j04/esmeval/bgc-val/mesh_mask_eORCA1_wrk.nc in /gws/nopw/j04/esmeval/bgc-val/mesh_mask_eORCA1_wrk.nc
NOT Changing FLAG: $PATHS_BGCVAL2 to /home/users/valeriu/bgcval2 in /gws/nopw/j04/esmeval/bgc-val/mesh_mask_eORCA1_wrk.nc
NOT Changing FLAG: $JOBID to u-cp416debug in /gws/nopw/j04/esmeval/bgc-val/mesh_mask_eORCA1_wrk.nc
NOT Changing FLAG: $MODEL to CICE in /gws/nopw/j04/esmeval/bgc-val/mesh_mask_eORCA1_wrk.nc
NOT Changing FLAG: $NAME to TotalIceExtent in /gws/nopw/j04/esmeval/bgc-val/mesh_mask_eORCA1_wrk.nc
Traceback (most recent call last):
  File "/home/users/valeriu/miniconda3-June2021/envs/bgval2/bin/analysis_compare", line 33, in <module>
    sys.exit(load_entry_point('BGCVal2', 'console_scripts', 'analysis_compare')())
  File "/home/users/valeriu/bgcval2/bgcval2/analysis_compare.py", line 3318, in main
    load_yml_and_run(compare_yml, config_user)
  File "/home/users/valeriu/bgcval2/bgcval2/analysis_compare.py", line 3243, in load_yml_and_run
    analysis_timeseries(
  File "/home/users/valeriu/bgcval2/bgcval2/analysis_timeseries.py", line 647, in analysis_timeseries
    av[key] = load_key_file(key, paths, jobID)
  File "/home/users/valeriu/bgcval2/bgcval2/analysis_timeseries.py", line 312, in load_key_file
    convert_func, kwargs = load_function(md_convert)
  File "/home/users/valeriu/bgcval2/bgcval2/analysis_timeseries.py", line 213, in load_function
    module = loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1029, in load_module
  File "<frozen importlib._bootstrap_external>", line 854, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/users/valeriu/bgcval2/bgcval2/functions/ice.py", line 34, in <module>
    from bgcval2.functions.get_kwarg_file import get_kwarg_file
ModuleNotFoundError: No module named 'bgcval2.functions.get_kwarg_file'
```

can you pls point me to a fully running version/branch and explicitly state what's the data that's needed for the run pls? :beer:

**Comment by ledm** [comment]
BGCVal v1 was not really made to run anywhere but jasmin. debug,yml is a fully but close to minimally running version. 

The synlinks and renaming of files, changing permissions and all that was set up because NEMO regularly changes the output format of the model data files. Small changes, big changes, naming conventions, permissions, all sorts of stuff. This link chain was set up to make sure they are regularly. You can't rename them, because then mass will just re-download the same file again. 

We could make a very small number of model files available within the repository, which may start to solve some of the headaches, while creating many many more.

**Comment by valeriupredoi** [comment]
Can we not run just the majority of the functionality of say, `anlaysis_compare`, (without any mass download, we can live with that, if we don't test the mass dll) with just a bit of portable sample data?

**Comment by ledm** [comment]
Yes, guess so, but we'd need to figure out how to set the changes to path.py. A lot of random data is needed for a standard analysis.

**Comment by valeriupredoi** [comment]
if you give me all those Orca and Nemo mask files (that actually make some sense, not filled with NaNs haha) etc I can set the test up :+1:

**Comment by valeriupredoi** [comment]
closing this (for now, at least) since we now have a modicum of end-to-end testing; I'd like to get Codecov in and see how much of the actual codebase is tested anyway
