### ISSUE TITLE
Pin `netCDF4 != 1.6.1`

### ISSUE THREAD

**Issue by valeriupredoi** [valeriupredoi/bgcval2#56]
@ledm heads up I had to pin netcdf4 to avoid the latest version (a few hours old) - that's hitting people with pretty nasty SegFaults - let me know if you have any issues, see the original Pull from ESMValCore https://github.com/ESMValGroup/ESMValCore/pull/1724

**Comment by ledm** [comment]
Okay, thanks for keeping up with this.

**Comment by valeriupredoi** [comment]
gonna close it since things look to be long)er) term at Unidata/netCDF4, see https://github.com/Unidata/netcdf4-python/issues/1192
