### ISSUE TITLE
Shelf mask

### ISSUE THREAD

**Issue by DrYool** [valeriupredoi/bgcval2#57]
I'd like to have a geographical mask that can be applied to separate shelf regions of the ocean (where the seafloor is 200m deep at most) from "deep ocean" regions which are deeper than 200m [*]. In the first place, adding this to the list of geographical splits that already happen would be good. While I can imagine reasons for wanting it combined with other masks (e.g. Arctic + shelf, North Atlantic + shelf), that's probably unnecessary at this point.

I'm happy to help with preparing any files needed to make the mask.

In conversation with Lee, it's possible that this mask may already exist, so ignore this request if so.

[*] 200m or 250m I should say.

**Comment by ledm** [comment]
Regions are defined here:
https://github.com/valeriupredoi/bgcval2/blob/main/bgcval2/bgcvaltools/makeMask.py 

(Yes, it needs better documentation!)

Good news: there is already an `OnShelf` and  `OffShelf` region, but this is defined to be defined at a depth of 500m. So, either you can use 500m, or edit the code and set it to the value that you want here:

https://github.com/valeriupredoi/bgcval2/blob/c1bdd014c93b12e5c7fbbbb77f0abff9582cfe89/bgcval2/bgcvaltools/makeMask.py#L446


Or if you think we'd want to keep both 200m/250m and 500m, we can write a new regional mask `OnShelf250` or similar and add it to this function.

**Comment by DrYool** [comment]
I think 500m is probably a little too deep for the shelf/off-shelf distinction. I think 250m is probably better, so I'll try to hack the code as you suggest. Of course, if it works, I'll then be back at you trying to upload it to github! :-)

**Comment by DrYool** [comment]
So that was easy to find and hack. However, I'm not 100% sure on where I ask for it. The example scripts I have to hand in my key_lists directory are aimed at showing global properties rather than ones involving regional masks. Is there an example I can look at?

**Comment by ledm** [comment]
You'll need to edit the individual key_files/*.yml files. You add the "onshelf" and "offshelf" to the regions line.

**Comment by ledm** [comment]
This should have been: `OnShelf` and `OffShelf`. I wrote it on my phone during a meeting - sorry!

**Comment by ledm** [comment]
Closed this issue via PR #58.

**Comment by valeriupredoi** [comment]
:llama:
