### ISSUE TITLE
update bgcval text in html to bgcval2!

### ISSUE THREAD

**Issue by ledm** [valeriupredoi/bgcval2#60]
Time to update our branch to bgcval2 in the final reports!

**Comment by ledm** [comment]
Possibly a good time to remove the "ukesm" specific stuff too. Like the logo, the title and so on.

**Comment by valeriupredoi** [comment]
Logo? Gonna replace it with the Porsche :laughing:

**Comment by valeriupredoi** [comment]
it looks like you've already done this, @ledm we should keep the formality to add "Closes #xx" in the PR so we autoclose issues when we merge PRs (I need to remind myself do that here too)

**Comment by ledm** [comment]
Nope, the html reports still
