### ISSUE TITLE
ESMValTool style modularisation

### ISSUE THREAD

**Issue by ledm** [valeriupredoi/bgcval2#72]
UKESM has changed its output netcdf format: it removed the mask! So we need to create our own masks. However, this needs to be done everywhere. This means that it needs to be added to every single function in `bgcval2/functions`.

Alternatively, I'd like to change every function so that they are modular instead, like ESMValTool. At the moment, a function both loads and applied some transformation today: ie:
```
def KtoC(nc,keys):
    """
    Loads keys[0] from the netcdf, and converts from Kelvin to Celcius.
    """
    return nc.variables[keys[0]][:] - 273.15
```
So every function takes a pre-loaded `netCDF4.Dataset` object, and a list of key names (strings), and occasionally additional kwargs. It then applied some function to those objects, and returns an arrray.

However, I propose to split the loading and the function int separate functions, such that each function only applies some operation to a list of arrays. ie:
```
def KtoC(arrays):
    """
    Converts from Kelvin to Celcius.
    """
   return [arr  - 273.15 for arr in arrays]
```

This means that with a bit of re-writing, we can do some boring stuff for every field behind the scenes. The loading, fixing the mask, etc. 

It also means that we can chain several functions together. It might make testing easier too?

**Comment by valeriupredoi** [comment]
yeah that's a very good call! I think I was yapping about this some months ago myself. We can do a hijack here - have an IO module that loads, fixes etc data and passes it as a `netCDF4.Dataset` object after it's done its work, so all those functions don't need to change

**Comment by valeriupredoi** [comment]
BTW that UKESM output change sounds to me like bug rather than a desired feature - nobody really wants 0 values that are not masked, unless one sets the fillValue or missing_value to 0 which is cavalier anyway since some data can be 0

**Comment by valeriupredoi** [comment]
let me have a crack at the IO, that should probably be quite straightforward since we only have this crap case for now, obv will make it so we can slot in more such turd pizzas :pizza:

**Comment by tillku** [comment]
Can we not load the mesh_mask file of UKESM into bgcval2 once and for all, so the mask doesn't have to be dealt with all the time?
