### ISSUE TITLE
A minor item for documentation

### ISSUE THREAD

**Issue by DrYool** [valeriupredoi/bgcval2#76]
The documentation is very good on getting the environment set and BGCval2 downloaded, but I've forgotten the best procedure for downloading an up-to-date instance when I've already got an installation with stuff I want to keep in it. Could there be a "refreshing your BGCval2 installation" paragraph in the main documentation? I've been told before but I've completely forgotten (sorry Lee!). Apologies in advance if my ignorance is so great that I haven't spotted the answer right in front of me!

I should add that this item is reflective of my sporadic (for now) use of BGCval2 for run analysis - I promised I'll get better once I have to look more routinely for UKESM2's spin-up, etc.

**Comment by valeriupredoi** [comment]
@DrYool that's a very good idea, cheers! I'll do that today 🍺
